# Generated by Django 5.2.5 on 2025-08-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('box_x1', models.FloatField()),
                ('box_y1', models.FloatField()),
                ('box_x2', models.FloatField()),
                ('box_y2', models.FloatField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='api.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_uri', models.TextField()),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='api.photo')),
            ],
        ),
    ]
