# Generated by Django 5.2.5 on 2025-08-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
