# Generated by Django 5.2.5 on 2025-08-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='crack_ration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
