# Generated by Django 5.2.5 on 2025-08-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photo_crack_ration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='crack_ration',
            new_name='crack_ratio',
        ),
    ]
